### ISSUE TITLE
Small issues with highlight and formatted text in a quote block

### ISSUE THREAD

**Issue by fagoliveira** [AllJavi/material_gruvbox_obsidian#1]
Hello, AllJavi.

First of all, thank you for creating this amazing theme! I prefer your color scheme over the Obsidian gruvbox because it's lighter in my eyes when working at night. I also prefer to work with ranges of yellow and red rather than blue, which is what most Obsidian color schemes present.

I'm writing to let you know that I've noticed two small issues with your color scheme that you might want to update, if you wish.

The first issue is related with the highlighted text in light mode. The dark mode highlighted text has a good background contrast, but the one in the light mode is too dark and barely readable. I've noticed that, in the dark mode, you correctly switched the text to a darker color, which is what makes the contrast between highlight and text color good. But, in the light mode, you retained the dark colored text, and this is what makes the text harder to read. Therefore, I applied a small change to your color scheme in light mode to match what you did in the dark mode:

From: --text-highlight-fg:             var(--dark-text);
To: --text-highlight-fg:             var(--light0-hard);

The second issue is related with bold and italic text when these are under a quote. In your current scheme, the bold and italics colors are not applied to text that is wrapped in a quote. To resolve the issue, I took inspiration from the Obsidian gruvbox theme, which does not have this issue, and added the following code block:

.cm-line .cm-strong
{
    color: var(--bold-color) !important;
}

.cm-line .cm-em
{
    color: var(--italic-color) !important;
}

I hope you appreciate this suggestions. And thanks again for your hard work!

**Comment by AllJavi** [comment]
I really like the changes, I just updated the theme styles with them. However, since they are minor modifications, I don't think I'll create a new version as such, because they would have to approve it again. So, if you want to update the changes, just reinstall the theme.
Thanks a lot
